//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_receiver
    {
        public int efile_receiver_id { get; set; }
        public string submission_id { get; set; }
        public byte[] send_submission_status { get; set; }
        public byte[] get_ack_status { get; set; }
        public string ack_xml { get; set; }
        public byte[] submission_status { get; set; }
        public byte[] schedule1 { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> create_time_stamp { get; set; }
        public Nullable<System.DateTime> update_time_stamp { get; set; }
        public string system_id { get; set; }
    }
}
