//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_error
    {
        public efile_error()
        {
            this.efile_email_log = new HashSet<efile_email_log>();
        }
    
        public int efile_error_id { get; set; }
        public string submission_id { get; set; }
        public string error_code { get; set; }
        public string error_message { get; set; }
        public string error_classification { get; set; }
        public string action { get; set; }
        public Nullable<byte> error_picked_up { get; set; }
        public Nullable<byte> error_fixed { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> create_time_stamp { get; set; }
        public Nullable<System.DateTime> update_time_stamp { get; set; }
    
        public virtual ICollection<efile_email_log> efile_email_log { get; set; }
    }
}
