//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_email_log
    {
        public int efile_email_log_id { get; set; }
        public string submission_id { get; set; }
        public int efile_error_id { get; set; }
        public int efile_email_template_id { get; set; }
        public string email_to { get; set; }
        public string email_from { get; set; }
        public string email_message { get; set; }
        public string email_subject { get; set; }
        public Nullable<bool> email_status { get; set; }
    
        public virtual efile_error efile_error { get; set; }
    }
}
