//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_hold
    {
        public efile_hold()
        {
            this.efile_comment = new HashSet<efile_comment>();
            this.efile_hold_attachment = new HashSet<efile_hold_attachment>();
            this.efile_irs_schema = new HashSet<efile_irs_schema>();
            this.efile_last_status = new HashSet<efile_last_status>();
            this.efile_log = new HashSet<efile_log>();
            this.efile_progress = new HashSet<efile_progress>();
            this.efile_sender = new HashSet<efile_sender>();
        }
    
        public long efile_hold_id { get; set; }
        public int sender_id { get; set; }
        public Nullable<long> return_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string tax_return_type_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public Nullable<int> no_of_attachments { get; set; }
        public string tax_object { get; set; }
        public string env_indicator { get; set; }
        public string efile_trans_id { get; set; }
        public string tax_year { get; set; }
        public string tax_period { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_time_stamp { get; set; }
        public System.DateTime update_time_stamp { get; set; }
        public string irs_system_id { get; set; }
    
        public virtual ICollection<efile_comment> efile_comment { get; set; }
        public virtual ICollection<efile_hold_attachment> efile_hold_attachment { get; set; }
        public virtual ICollection<efile_irs_schema> efile_irs_schema { get; set; }
        public virtual ICollection<efile_last_status> efile_last_status { get; set; }
        public virtual ICollection<efile_log> efile_log { get; set; }
        public virtual ICollection<efile_progress> efile_progress { get; set; }
        public virtual ICollection<efile_sender> efile_sender { get; set; }
    }
}
