//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_name_control
    {
        public long efile_name_control_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> business_info_id { get; set; }
        public string business_info_name { get; set; }
        public Nullable<long> return_id { get; set; }
        public string name_control { get; set; }
    }
}
