//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Tax1040_EfileEntities : DbContext
    {
        public Tax1040_EfileEntities()
            : base("name=Tax1040_EfileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<efile_comment> efile_comment { get; set; }
        public DbSet<efile_email_log> efile_email_log { get; set; }
        public DbSet<efile_error> efile_error { get; set; }
        public DbSet<efile_hold> efile_hold { get; set; }
        public DbSet<efile_hold_attachment> efile_hold_attachment { get; set; }
        public DbSet<efile_irs_schema> efile_irs_schema { get; set; }
        public DbSet<efile_last_status> efile_last_status { get; set; }
        public DbSet<efile_log> efile_log { get; set; }
        public DbSet<efile_name_control> efile_name_control { get; set; }
        public DbSet<efile_progress> efile_progress { get; set; }
        public DbSet<efile_receiver> efile_receiver { get; set; }
        public DbSet<efile_request_response> efile_request_response { get; set; }
        public DbSet<efile_sender> efile_sender { get; set; }
        public DbSet<efile_transmit> efile_transmit { get; set; }
        public DbSet<fax_log> fax_log { get; set; }
        public DbSet<sms_log> sms_log { get; set; }
        public DbSet<StcErrorCode> StcErrorCodes { get; set; }
    
        public virtual int usp_admin_efile_last_status_update(Nullable<long> efile_hold_id, string stage, string state)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_admin_efile_last_status_update", efile_hold_idParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_admin_find_name_control(Nullable<long> return_id)
        {
            var return_idParameter = return_id.HasValue ?
                new ObjectParameter("return_id", return_id) :
                new ObjectParameter("return_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_admin_find_name_control", return_idParameter);
        }
    
        public virtual int usp_admin_get_efile_status_report(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_admin_get_efile_status_report", dateParameter);
        }
    
        public virtual int usp_efile_comment_get(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_comment_get", efile_hold_idParameter);
        }
    
        public virtual int usp_efile_comment_insert(Nullable<long> efile_hold_id, string efile_comment, Nullable<long> admin_users_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            var efile_commentParameter = efile_comment != null ?
                new ObjectParameter("efile_comment", efile_comment) :
                new ObjectParameter("efile_comment", typeof(string));
    
            var admin_users_idParameter = admin_users_id.HasValue ?
                new ObjectParameter("admin_users_id", admin_users_id) :
                new ObjectParameter("admin_users_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_comment_insert", efile_hold_idParameter, efile_commentParameter, admin_users_idParameter);
        }
    
        public virtual int usp_efile_error_insert(string submission_id, string error_code, string error_message, string error_classification, string action, Nullable<int> status_id, string stage, string state)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var error_codeParameter = error_code != null ?
                new ObjectParameter("error_code", error_code) :
                new ObjectParameter("error_code", typeof(string));
    
            var error_messageParameter = error_message != null ?
                new ObjectParameter("error_message", error_message) :
                new ObjectParameter("error_message", typeof(string));
    
            var error_classificationParameter = error_classification != null ?
                new ObjectParameter("error_classification", error_classification) :
                new ObjectParameter("error_classification", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_error_insert", submission_idParameter, error_codeParameter, error_messageParameter, error_classificationParameter, actionParameter, status_idParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_efile_error_irs_schema_create(string submissionID, string errorCode, string errormessage, string errorClassification, string action, string errorType)
        {
            var submissionIDParameter = submissionID != null ?
                new ObjectParameter("SubmissionID", submissionID) :
                new ObjectParameter("SubmissionID", typeof(string));
    
            var errorCodeParameter = errorCode != null ?
                new ObjectParameter("ErrorCode", errorCode) :
                new ObjectParameter("ErrorCode", typeof(string));
    
            var errormessageParameter = errormessage != null ?
                new ObjectParameter("Errormessage", errormessage) :
                new ObjectParameter("Errormessage", typeof(string));
    
            var errorClassificationParameter = errorClassification != null ?
                new ObjectParameter("ErrorClassification", errorClassification) :
                new ObjectParameter("ErrorClassification", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var errorTypeParameter = errorType != null ?
                new ObjectParameter("ErrorType", errorType) :
                new ObjectParameter("ErrorType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_error_irs_schema_create", submissionIDParameter, errorCodeParameter, errormessageParameter, errorClassificationParameter, actionParameter, errorTypeParameter);
        }
    
        public virtual int usp_efile_error_picked_up_update(Nullable<int> efile_error_id)
        {
            var efile_error_idParameter = efile_error_id.HasValue ?
                new ObjectParameter("efile_error_id", efile_error_id) :
                new ObjectParameter("efile_error_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_error_picked_up_update", efile_error_idParameter);
        }
    
        public virtual ObjectResult<usp_efile_hold_attachment_get_on_efile_hold_id_Result> usp_efile_hold_attachment_get_on_efile_hold_id(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_hold_attachment_get_on_efile_hold_id_Result>("usp_efile_hold_attachment_get_on_efile_hold_id", efile_hold_idParameter);
        }
    
        public virtual int usp_efile_hold_attachment_insert(Nullable<int> efile_hold_id, byte[] efile_attachment, string type, string attachment_name)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(int));
    
            var efile_attachmentParameter = efile_attachment != null ?
                new ObjectParameter("efile_attachment", efile_attachment) :
                new ObjectParameter("efile_attachment", typeof(byte[]));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var attachment_nameParameter = attachment_name != null ?
                new ObjectParameter("attachment_name", attachment_name) :
                new ObjectParameter("attachment_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_hold_attachment_insert", efile_hold_idParameter, efile_attachmentParameter, typeParameter, attachment_nameParameter);
        }
    
        public virtual ObjectResult<usp_efile_hold_get_by_id_Result> usp_efile_hold_get_by_id(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_hold_get_by_id_Result>("usp_efile_hold_get_by_id", efile_hold_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_efile_hold_get_irs_schema_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_efile_hold_get_irs_schema_count");
        }
    
        public virtual ObjectResult<usp_efile_hold_get_on_id_Result> usp_efile_hold_get_on_id(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_hold_get_on_id_Result>("usp_efile_hold_get_on_id", efile_hold_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_efile_hold_persist(Nullable<int> sender_id, Nullable<int> return_id, Nullable<int> user_id, string user_name, Nullable<int> no_of_attachments, string user_email, string tax_object, string env_indicator, string efile_trans_id, Nullable<int> status_id, string stage, string state, string tax_return_type_id, string tax_year, string tax_period)
        {
            var sender_idParameter = sender_id.HasValue ?
                new ObjectParameter("sender_id", sender_id) :
                new ObjectParameter("sender_id", typeof(int));
    
            var return_idParameter = return_id.HasValue ?
                new ObjectParameter("return_id", return_id) :
                new ObjectParameter("return_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var no_of_attachmentsParameter = no_of_attachments.HasValue ?
                new ObjectParameter("no_of_attachments", no_of_attachments) :
                new ObjectParameter("no_of_attachments", typeof(int));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var tax_objectParameter = tax_object != null ?
                new ObjectParameter("tax_object", tax_object) :
                new ObjectParameter("tax_object", typeof(string));
    
            var env_indicatorParameter = env_indicator != null ?
                new ObjectParameter("env_indicator", env_indicator) :
                new ObjectParameter("env_indicator", typeof(string));
    
            var efile_trans_idParameter = efile_trans_id != null ?
                new ObjectParameter("efile_trans_id", efile_trans_id) :
                new ObjectParameter("efile_trans_id", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var tax_return_type_idParameter = tax_return_type_id != null ?
                new ObjectParameter("tax_return_type_id", tax_return_type_id) :
                new ObjectParameter("tax_return_type_id", typeof(string));
    
            var tax_yearParameter = tax_year != null ?
                new ObjectParameter("tax_year", tax_year) :
                new ObjectParameter("tax_year", typeof(string));
    
            var tax_periodParameter = tax_period != null ?
                new ObjectParameter("tax_period", tax_period) :
                new ObjectParameter("tax_period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_efile_hold_persist", sender_idParameter, return_idParameter, user_idParameter, user_nameParameter, no_of_attachmentsParameter, user_emailParameter, tax_objectParameter, env_indicatorParameter, efile_trans_idParameter, status_idParameter, stageParameter, stateParameter, tax_return_type_idParameter, tax_yearParameter, tax_periodParameter);
        }
    
        public virtual ObjectResult<usp_efile_irs_schema_get_on_efile_hold_id_Result> usp_efile_irs_schema_get_on_efile_hold_id(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_irs_schema_get_on_efile_hold_id_Result>("usp_efile_irs_schema_get_on_efile_hold_id", efile_hold_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_efile_irs_schema_get_today_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_efile_irs_schema_get_today_count");
        }
    
        public virtual int usp_efile_irs_schema_insert(Nullable<int> efile_hold_id, string efile_irs_schema, string manifest_xml, string submission_id, Nullable<int> status_id, string stage, string state)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(int));
    
            var efile_irs_schemaParameter = efile_irs_schema != null ?
                new ObjectParameter("efile_irs_schema", efile_irs_schema) :
                new ObjectParameter("efile_irs_schema", typeof(string));
    
            var manifest_xmlParameter = manifest_xml != null ?
                new ObjectParameter("manifest_xml", manifest_xml) :
                new ObjectParameter("manifest_xml", typeof(string));
    
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_irs_schema_insert", efile_hold_idParameter, efile_irs_schemaParameter, manifest_xmlParameter, submission_idParameter, status_idParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_efile_irs_schema_persist(Nullable<int> efile_hold_id, string efile_irs_schema, string manifest_xml, string submission_id, Nullable<int> status_id, string old_submission_id, string stage, string state)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(int));
    
            var efile_irs_schemaParameter = efile_irs_schema != null ?
                new ObjectParameter("efile_irs_schema", efile_irs_schema) :
                new ObjectParameter("efile_irs_schema", typeof(string));
    
            var manifest_xmlParameter = manifest_xml != null ?
                new ObjectParameter("manifest_xml", manifest_xml) :
                new ObjectParameter("manifest_xml", typeof(string));
    
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var old_submission_idParameter = old_submission_id != null ?
                new ObjectParameter("old_submission_id", old_submission_id) :
                new ObjectParameter("old_submission_id", typeof(string));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_irs_schema_persist", efile_hold_idParameter, efile_irs_schemaParameter, manifest_xmlParameter, submission_idParameter, status_idParameter, old_submission_idParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_efile_name_control_persist(string submission_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_name_control_persist", submission_idParameter);
        }
    
        public virtual int usp_efile_receiver_insert(string submission_id, byte[] send_submission_status, byte[] get_ack_status, byte[] submission_status, byte[] schedule1, string ack_xml, Nullable<int> status_id, string stage, string state, string irs_system_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var send_submission_statusParameter = send_submission_status != null ?
                new ObjectParameter("send_submission_status", send_submission_status) :
                new ObjectParameter("send_submission_status", typeof(byte[]));
    
            var get_ack_statusParameter = get_ack_status != null ?
                new ObjectParameter("get_ack_status", get_ack_status) :
                new ObjectParameter("get_ack_status", typeof(byte[]));
    
            var submission_statusParameter = submission_status != null ?
                new ObjectParameter("submission_status", submission_status) :
                new ObjectParameter("submission_status", typeof(byte[]));
    
            var schedule1Parameter = schedule1 != null ?
                new ObjectParameter("schedule1", schedule1) :
                new ObjectParameter("schedule1", typeof(byte[]));
    
            var ack_xmlParameter = ack_xml != null ?
                new ObjectParameter("ack_xml", ack_xml) :
                new ObjectParameter("ack_xml", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var irs_system_idParameter = irs_system_id != null ?
                new ObjectParameter("irs_system_id", irs_system_id) :
                new ObjectParameter("irs_system_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_receiver_insert", submission_idParameter, send_submission_statusParameter, get_ack_statusParameter, submission_statusParameter, schedule1Parameter, ack_xmlParameter, status_idParameter, stageParameter, stateParameter, irs_system_idParameter);
        }
    
        public virtual int usp_efile_receiver_update(string submissionID, string receiverType, byte[] attachmentStatus, string ackXML, Nullable<int> statusID, string stage, string state)
        {
            var submissionIDParameter = submissionID != null ?
                new ObjectParameter("SubmissionID", submissionID) :
                new ObjectParameter("SubmissionID", typeof(string));
    
            var receiverTypeParameter = receiverType != null ?
                new ObjectParameter("ReceiverType", receiverType) :
                new ObjectParameter("ReceiverType", typeof(string));
    
            var attachmentStatusParameter = attachmentStatus != null ?
                new ObjectParameter("AttachmentStatus", attachmentStatus) :
                new ObjectParameter("AttachmentStatus", typeof(byte[]));
    
            var ackXMLParameter = ackXML != null ?
                new ObjectParameter("AckXML", ackXML) :
                new ObjectParameter("AckXML", typeof(string));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("Stage", stage) :
                new ObjectParameter("Stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_receiver_update", submissionIDParameter, receiverTypeParameter, attachmentStatusParameter, ackXMLParameter, statusIDParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_efile_request_response_create(string submission_id, string request, string message_id, string response, string error_code, string error_message, string error_classification, string action, string service_action, Nullable<byte> status_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("request", request) :
                new ObjectParameter("request", typeof(string));
    
            var message_idParameter = message_id != null ?
                new ObjectParameter("message_id", message_id) :
                new ObjectParameter("message_id", typeof(string));
    
            var responseParameter = response != null ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(string));
    
            var error_codeParameter = error_code != null ?
                new ObjectParameter("error_code", error_code) :
                new ObjectParameter("error_code", typeof(string));
    
            var error_messageParameter = error_message != null ?
                new ObjectParameter("error_message", error_message) :
                new ObjectParameter("error_message", typeof(string));
    
            var error_classificationParameter = error_classification != null ?
                new ObjectParameter("error_classification", error_classification) :
                new ObjectParameter("error_classification", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var service_actionParameter = service_action != null ?
                new ObjectParameter("service_action", service_action) :
                new ObjectParameter("service_action", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_request_response_create", submission_idParameter, requestParameter, message_idParameter, responseParameter, error_codeParameter, error_messageParameter, error_classificationParameter, actionParameter, service_actionParameter, status_idParameter);
        }
    
        public virtual ObjectResult<usp_efile_schema_get_by_id_Result> usp_efile_schema_get_by_id(string submission_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_schema_get_by_id_Result>("usp_efile_schema_get_by_id", submission_idParameter);
        }
    
        public virtual int usp_efile_search(Nullable<long> return_id, string business_name, string ein, string submission_id, Nullable<System.DateTime> date, string description, Nullable<int> form_type)
        {
            var return_idParameter = return_id.HasValue ?
                new ObjectParameter("return_id", return_id) :
                new ObjectParameter("return_id", typeof(long));
    
            var business_nameParameter = business_name != null ?
                new ObjectParameter("business_name", business_name) :
                new ObjectParameter("business_name", typeof(string));
    
            var einParameter = ein != null ?
                new ObjectParameter("ein", ein) :
                new ObjectParameter("ein", typeof(string));
    
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var form_typeParameter = form_type.HasValue ?
                new ObjectParameter("form_type", form_type) :
                new ObjectParameter("form_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_search", return_idParameter, business_nameParameter, einParameter, submission_idParameter, dateParameter, descriptionParameter, form_typeParameter);
        }
    
        public virtual int usp_efile_sender_persist(Nullable<int> efile_hold_id, byte[] dime_attachment, string submission_id, string message_id, Nullable<byte> status_id, string stage, string state)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(int));
    
            var dime_attachmentParameter = dime_attachment != null ?
                new ObjectParameter("dime_attachment", dime_attachment) :
                new ObjectParameter("dime_attachment", typeof(byte[]));
    
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var message_idParameter = message_id != null ?
                new ObjectParameter("message_id", message_id) :
                new ObjectParameter("message_id", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(byte));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_sender_persist", efile_hold_idParameter, dime_attachmentParameter, submission_idParameter, message_idParameter, status_idParameter, stageParameter, stateParameter);
        }
    
        public virtual ObjectResult<usp_efile_transmit_get_all_Result> usp_efile_transmit_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_efile_transmit_get_all_Result>("usp_efile_transmit_get_all");
        }
    
        public virtual int usp_efile_transmit_persist(Nullable<long> user_id, Nullable<long> return_id, string return_type, string stage, string state, string ip_date_time, string ip_time_zone, string ip_address, Nullable<int> status_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            var return_idParameter = return_id.HasValue ?
                new ObjectParameter("return_id", return_id) :
                new ObjectParameter("return_id", typeof(long));
    
            var return_typeParameter = return_type != null ?
                new ObjectParameter("return_type", return_type) :
                new ObjectParameter("return_type", typeof(string));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var ip_date_timeParameter = ip_date_time != null ?
                new ObjectParameter("ip_date_time", ip_date_time) :
                new ObjectParameter("ip_date_time", typeof(string));
    
            var ip_time_zoneParameter = ip_time_zone != null ?
                new ObjectParameter("ip_time_zone", ip_time_zone) :
                new ObjectParameter("ip_time_zone", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_transmit_persist", user_idParameter, return_idParameter, return_typeParameter, stageParameter, stateParameter, ip_date_timeParameter, ip_time_zoneParameter, ip_addressParameter, status_idParameter);
        }
    
        public virtual int usp_efile_transmit_update(Nullable<long> efile_transmit_id, string state)
        {
            var efile_transmit_idParameter = efile_transmit_id.HasValue ?
                new ObjectParameter("efile_transmit_id", efile_transmit_id) :
                new ObjectParameter("efile_transmit_id", typeof(long));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efile_transmit_update", efile_transmit_idParameter, stateParameter);
        }
    
        public virtual int usp_efiled_users(string form_type)
        {
            var form_typeParameter = form_type != null ?
                new ObjectParameter("form_type", form_type) :
                new ObjectParameter("form_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efiled_users", form_typeParameter);
        }
    
        public virtual int usp_efiled_users_by_id(Nullable<int> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_efiled_users_by_id", efile_hold_idParameter);
        }
    
        public virtual int usp_get_admin_efile_count(Nullable<System.DateTime> from_date, Nullable<System.DateTime> to_date, Nullable<long> product_id)
        {
            var from_dateParameter = from_date.HasValue ?
                new ObjectParameter("from_date", from_date) :
                new ObjectParameter("from_date", typeof(System.DateTime));
    
            var to_dateParameter = to_date.HasValue ?
                new ObjectParameter("to_date", to_date) :
                new ObjectParameter("to_date", typeof(System.DateTime));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_admin_efile_count", from_dateParameter, to_dateParameter, product_idParameter);
        }
    
        public virtual int usp_get_admin_efile_status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_admin_efile_status");
        }
    
        public virtual ObjectResult<usp_get_efile_acknowledge_on_status_Result> usp_get_efile_acknowledge_on_status(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_acknowledge_on_status_Result>("usp_get_efile_acknowledge_on_status", stageParameter, stateParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_attachement_and_xml_by_efile_trans_id_Result> usp_get_efile_attachement_and_xml_by_efile_trans_id(string efile_trans_id)
        {
            var efile_trans_idParameter = efile_trans_id != null ?
                new ObjectParameter("efile_trans_id", efile_trans_id) :
                new ObjectParameter("efile_trans_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_attachement_and_xml_by_efile_trans_id_Result>("usp_get_efile_attachement_and_xml_by_efile_trans_id", efile_trans_idParameter);
        }
    
        public virtual int usp_get_efile_error_from_error_code()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_error_from_error_code");
        }
    
        public virtual int usp_get_efile_error_on_id(Nullable<int> efile_error_id)
        {
            var efile_error_idParameter = efile_error_id.HasValue ?
                new ObjectParameter("efile_error_id", efile_error_id) :
                new ObjectParameter("efile_error_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_error_on_id", efile_error_idParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_error_on_submission_id_Result> usp_get_efile_error_on_submission_id(string submission_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_error_on_submission_id_Result>("usp_get_efile_error_on_submission_id", submission_idParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_error_on_transmission_id_Result> usp_get_efile_error_on_transmission_id(string efile_trans_id)
        {
            var efile_trans_idParameter = efile_trans_id != null ?
                new ObjectParameter("efile_trans_id", efile_trans_id) :
                new ObjectParameter("efile_trans_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_error_on_transmission_id_Result>("usp_get_efile_error_on_transmission_id", efile_trans_idParameter);
        }
    
        public virtual int usp_get_efile_hold_records_on_acknowledgement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_hold_records_on_acknowledgement");
        }
    
        public virtual ObjectResult<usp_get_efile_hold_records_on_status_Result> usp_get_efile_hold_records_on_status(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_hold_records_on_status_Result>("usp_get_efile_hold_records_on_status", stageParameter, stateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_get_efile_hold_sender_count(Nullable<int> sender_id)
        {
            var sender_idParameter = sender_id.HasValue ?
                new ObjectParameter("sender_id", sender_id) :
                new ObjectParameter("sender_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_get_efile_hold_sender_count", sender_idParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_info_on_stage_status_Result> usp_get_efile_info_on_stage_status(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_info_on_stage_status_Result>("usp_get_efile_info_on_stage_status", stageParameter, stateParameter);
        }
    
        public virtual int usp_get_efile_irs_schema_on_status(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("Stage", stage) :
                new ObjectParameter("Stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_irs_schema_on_status", stageParameter, stateParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_name_control_Result> usp_get_efile_name_control(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_name_control_Result>("usp_get_efile_name_control", efile_hold_idParameter);
        }
    
        public virtual int usp_get_efile_name_control_on_efile_hold_id(Nullable<long> efile_hold_id)
        {
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_name_control_on_efile_hold_id", efile_hold_idParameter);
        }
    
        public virtual int usp_get_efile_req_res_by_action_and_time(string action, string start_time, string end_time, string date, string last_hours, string form_type)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var start_timeParameter = start_time != null ?
                new ObjectParameter("start_time", start_time) :
                new ObjectParameter("start_time", typeof(string));
    
            var end_timeParameter = end_time != null ?
                new ObjectParameter("end_time", end_time) :
                new ObjectParameter("end_time", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var last_hoursParameter = last_hours != null ?
                new ObjectParameter("last_hours", last_hours) :
                new ObjectParameter("last_hours", typeof(string));
    
            var form_typeParameter = form_type != null ?
                new ObjectParameter("form_type", form_type) :
                new ObjectParameter("form_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_efile_req_res_by_action_and_time", actionParameter, start_timeParameter, end_timeParameter, dateParameter, last_hoursParameter, form_typeParameter);
        }
    
        public virtual ObjectResult<usp_get_efile_sender_on_status_Result> usp_get_efile_sender_on_status(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("Stage", stage) :
                new ObjectParameter("Stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_efile_sender_on_status_Result>("usp_get_efile_sender_on_status", stageParameter, stateParameter);
        }
    
        public virtual int usp_get_latest_efile_status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_latest_efile_status");
        }
    
        public virtual int usp_get_rejected_efile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_rejected_efile");
        }
    
        public virtual int usp_get_rpt_payment_and_efile_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_rpt_payment_and_efile_count");
        }
    
        public virtual ObjectResult<byte[]> usp_get_schedule1(string efile_trans_id)
        {
            var efile_trans_idParameter = efile_trans_id != null ?
                new ObjectParameter("efile_trans_id", efile_trans_id) :
                new ObjectParameter("efile_trans_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("usp_get_schedule1", efile_trans_idParameter);
        }
    
        public virtual ObjectResult<usp_get_submission_id_for_acknowledgement_Result> usp_get_submission_id_for_acknowledgement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_submission_id_for_acknowledgement_Result>("usp_get_submission_id_for_acknowledgement");
        }
    
        public virtual ObjectResult<usp_get_submissions_Result> usp_get_submissions(string form_type)
        {
            var form_typeParameter = form_type != null ?
                new ObjectParameter("form_type", form_type) :
                new ObjectParameter("form_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_submissions_Result>("usp_get_submissions", form_typeParameter);
        }
    
        public virtual ObjectResult<usp_get_submissions_for_sender_channel_Result> usp_get_submissions_for_sender_channel(string stage, string state)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_submissions_for_sender_channel_Result>("usp_get_submissions_for_sender_channel", stageParameter, stateParameter);
        }
    
        public virtual ObjectResult<usp_rejected_efile_get_on_id_Result> usp_rejected_efile_get_on_id(string submission_id)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_rejected_efile_get_on_id_Result>("usp_rejected_efile_get_on_id", submission_idParameter);
        }
    
        public virtual int usp_rpt_get_payment_and_efile_count_old()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_rpt_get_payment_and_efile_count_old");
        }
    
        public virtual ObjectResult<Nullable<long>> usp_status_update(string submission_id, Nullable<long> efile_hold_id, Nullable<int> status_id, string stage, string state)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("usp_status_update", submission_idParameter, efile_hold_idParameter, status_idParameter, stageParameter, stateParameter);
        }
    
        public virtual int usp_update_system_status(string irs_system_id, Nullable<long> efile_hold_id)
        {
            var irs_system_idParameter = irs_system_id != null ?
                new ObjectParameter("irs_system_id", irs_system_id) :
                new ObjectParameter("irs_system_id", typeof(string));
    
            var efile_hold_idParameter = efile_hold_id.HasValue ?
                new ObjectParameter("efile_hold_id", efile_hold_id) :
                new ObjectParameter("efile_hold_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_system_status", irs_system_idParameter, efile_hold_idParameter);
        }
    
        public virtual int usp_upload_files(string submission_id, byte[] zip, byte[] get_ack_status, byte[] schedule1, string stage, string state)
        {
            var submission_idParameter = submission_id != null ?
                new ObjectParameter("submission_id", submission_id) :
                new ObjectParameter("submission_id", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(byte[]));
    
            var get_ack_statusParameter = get_ack_status != null ?
                new ObjectParameter("get_ack_status", get_ack_status) :
                new ObjectParameter("get_ack_status", typeof(byte[]));
    
            var schedule1Parameter = schedule1 != null ?
                new ObjectParameter("schedule1", schedule1) :
                new ObjectParameter("schedule1", typeof(byte[]));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_upload_files", submission_idParameter, zipParameter, get_ack_statusParameter, schedule1Parameter, stageParameter, stateParameter);
        }
    }
}
