//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public long address_id { get; set; }
        public long personal_info_id { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public Nullable<long> personal_address_state_id { get; set; }
        public string foreign_state { get; set; }
        public Nullable<long> country_id { get; set; }
        public string zip_code { get; set; }
        public string phone { get; set; }
        public int address_type { get; set; }
        public Nullable<long> residence_state_id { get; set; }
        public Nullable<bool> has_lived_in_more_than_one_state { get; set; }
        public Nullable<bool> has_earned_income_from_non_lived_state { get; set; }
        public Nullable<long> lived_in_another_state_id { get; set; }
        public Nullable<System.DateTime> lived_in_another_state_from { get; set; }
        public Nullable<System.DateTime> lived_in_another_state_to { get; set; }
        public Nullable<long> earned_income_from_non_lived_state_id { get; set; }
        public string apartment_number { get; set; }
        public string postal_code { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_datetime { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual country country { get; set; }
        public virtual state state { get; set; }
        public virtual state state1 { get; set; }
        public virtual state state2 { get; set; }
        public virtual personal_info personal_info { get; set; }
        public virtual state state3 { get; set; }
    }
}
