//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_feature_sku
    {
        public long state_feature_sku_id { get; set; }
        public long product_id { get; set; }
        public long feature_id { get; set; }
        public long state_id { get; set; }
        public decimal price { get; set; }
        public bool is_active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_datetime { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual state state { get; set; }
    }
}
