//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.addresses = new HashSet<address>();
            this.addresses1 = new HashSet<address>();
            this.addresses2 = new HashSet<address>();
            this.addresses3 = new HashSet<address>();
            this.personal_info = new HashSet<personal_info>();
            this.state_feature_sku = new HashSet<state_feature_sku>();
            this.state_zip_code_conditions = new HashSet<state_zip_code_conditions>();
        }
    
        public long state_id { get; set; }
        public string state_code { get; set; }
        public string state_name { get; set; }
        public bool is_active { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_datetime { get; set; }
        public System.DateTime update_datetime { get; set; }
        public Nullable<bool> is_additional_mailing_address { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<address> addresses1 { get; set; }
        public virtual ICollection<address> addresses2 { get; set; }
        public virtual ICollection<address> addresses3 { get; set; }
        public virtual ICollection<personal_info> personal_info { get; set; }
        public virtual ICollection<state_feature_sku> state_feature_sku { get; set; }
        public virtual ICollection<state_zip_code_conditions> state_zip_code_conditions { get; set; }
    }
}
