//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tax1040Entities : DbContext
    {
        public Tax1040Entities()
            : base("name=Tax1040Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<country> countries { get; set; }
        public DbSet<filing_status> filing_status { get; set; }
        public DbSet<person_type> person_type { get; set; }
        public DbSet<personal_info> personal_info { get; set; }
        public DbSet<state> states { get; set; }
        public DbSet<state_feature_sku> state_feature_sku { get; set; }
        public DbSet<state_zip_code_conditions> state_zip_code_conditions { get; set; }
        public DbSet<user> users { get; set; }
    }
}
