//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.personal_info = new HashSet<personal_info>();
        }
    
        public long user_id { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public Nullable<int> security_question_id { get; set; }
        public string security_answer { get; set; }
        public string client_IP { get; set; }
        public Nullable<long> password_reset_code { get; set; }
        public bool is_remember { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    
        public virtual ICollection<personal_info> personal_info { get; set; }
    }
}
