//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.TAX1040.Admin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_admin_role
    {
        public long user_admin_role_id { get; set; }
        public long user_admin_id { get; set; }
        public long admin_role_id { get; set; }
        public string role_name { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_datetime { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual admin_role admin_role { get; set; }
        public virtual user_admin user_admin { get; set; }
    }
}
