//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JTL.Tax1040.BusinessLogic.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username or Password entered is Incorrect. Please confirm your entries..
        /// </summary>
        public static string SIGNIN_INVALID_USER_NAME_PASSWORD_V {
            get {
                return ResourceManager.GetString("SIGNIN_INVALID_USER_NAME_PASSWORD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not be Empty..
        /// </summary>
        public static string SIGNIN_MISSING_PASSWORD_RF {
            get {
                return ResourceManager.GetString("SIGNIN_MISSING_PASSWORD_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not be Empty..
        /// </summary>
        public static string SIGNIN_MISSING_USER_NAME_RF {
            get {
                return ResourceManager.GetString("SIGNIN_MISSING_USER_NAME_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password can&apos;t be left Empty..
        /// </summary>
        public static string SIGNINISSUE_CONFORM_PASSWORD_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_CONFORM_PASSWORD_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered Incorrect Information. Please confirm all your entries..
        /// </summary>
        public static string SIGNINISSUE_INCORRECT_INFORMATION_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_INCORRECT_INFORMATION_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must be same. Try again?.
        /// </summary>
        public static string SIGNINISSUE_INVALID_CONFORM_PASSWORD_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_INVALID_CONFORM_PASSWORD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid Email Address. Please enter a valid Email Address..
        /// </summary>
        public static string SIGNINISSUE_INVALID_EMAIL_ID_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_INVALID_EMAIL_ID_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 8 to 15 characters with at least one alphabet, one number, and one special character..
        /// </summary>
        public static string SIGNINISSUE_INVALID_PASSWORD_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_INVALID_PASSWORD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered the Invalid Secret Code. Please enter the valid Secret Code sent to your Email address..
        /// </summary>
        public static string SIGNINISSUE_INVALID_SECRET_CODE_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_INVALID_SECRET_CODE_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Date of Birth has been omitted. This information is critical for tax filing purpose..
        /// </summary>
        public static string SIGNINISSUE_MISSING_DATE_OF_BIRTH_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_DATE_OF_BIRTH_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can&apos;t be left empty..
        /// </summary>
        public static string SIGNINISSUE_MISSING_EMAIL_ADDRESS_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_EMAIL_ADDRESS_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First Name has not been entered..
        /// </summary>
        public static string SIGNINISSUE_MISSING_FIRST_NAME_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_FIRST_NAME_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First Name can only have alphabets. Special characters, numbers and Punctuations can&apos;t be used..
        /// </summary>
        public static string SIGNINISSUE_MISSING_FIRST_NAME_SPECIALS_CHARACTER_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_FIRST_NAME_SPECIALS_CHARACTER_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Name has not been entered..
        /// </summary>
        public static string SIGNINISSUE_MISSING_LAST_NAME_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_LAST_NAME_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Name can only have alphabets. Special characters, numbers and Punctuations can&apos;t be used..
        /// </summary>
        public static string SIGNINISSUE_MISSING_LAST_NAME_SPECIALS_CHARACTER_V {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_LAST_NAME_SPECIALS_CHARACTER_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address can&apos;t be left empty..
        /// </summary>
        public static string SIGNINISSUE_MISSING_NEW_EMAIL_ADDRESS_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_NEW_EMAIL_ADDRESS_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password should not be Empty.
        /// </summary>
        public static string SIGNINISSUE_MISSING_NEW_PASSWORD_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_NEW_PASSWORD_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t skip the Security Question. Select one from the list!.
        /// </summary>
        public static string SIGNINISSUE_MISSING_SECRET_ANSWER_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_SECRET_ANSWER_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave Secret Code empty. Please enter the Secret Code sent to your Email address..
        /// </summary>
        public static string SIGNINISSUE_MISSING_SECRET_CODE_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_SECRET_CODE_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be left empty. Please give a Username of your choice..
        /// </summary>
        public static string SIGNINISSUE_MISSING_USERNAME_RF {
            get {
                return ResourceManager.GetString("SIGNINISSUE_MISSING_USERNAME_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This Email ID already exists..
        /// </summary>
        public static string SIGNUP_EXISTING_EMAIL_V {
            get {
                return ResourceManager.GetString("SIGNUP_EXISTING_EMAIL_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This Username already exists..
        /// </summary>
        public static string SIGNUP_EXISTING_USER_NAME_V {
            get {
                return ResourceManager.GetString("SIGNUP_EXISTING_USER_NAME_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid Email Address. Please enter a valid Email Address..
        /// </summary>
        public static string SIGNUP_INVALID_EMAIL_V {
            get {
                return ResourceManager.GetString("SIGNUP_INVALID_EMAIL_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 8 to 15 characters with at least one alphabet, one number, and one special character..
        /// </summary>
        public static string SIGNUP_INVALID_PASSWORD_V {
            get {
                return ResourceManager.GetString("SIGNUP_INVALID_PASSWORD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username must have at least 6 Characters which may include alphabets, numbers and underscore..
        /// </summary>
        public static string SIGNUP_INVALID_USER_NAME_V {
            get {
                return ResourceManager.GetString("SIGNUP_INVALID_USER_NAME_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is missing..
        /// </summary>
        public static string SIGNUP_MISSING_EMAIL_RF {
            get {
                return ResourceManager.GetString("SIGNUP_MISSING_EMAIL_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is missing..
        /// </summary>
        public static string SIGNUP_MISSING_PASSWORD_V {
            get {
                return ResourceManager.GetString("SIGNUP_MISSING_PASSWORD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer for Security Question is missing..
        /// </summary>
        public static string SIGNUP_MISSING_SECURITY_ANSWER_RF {
            get {
                return ResourceManager.GetString("SIGNUP_MISSING_SECURITY_ANSWER_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question is not selected..
        /// </summary>
        public static string SIGNUP_MISSING_SECURITY_QUESTION_RF {
            get {
                return ResourceManager.GetString("SIGNUP_MISSING_SECURITY_QUESTION_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is missing..
        /// </summary>
        public static string SIGNUP_MISSING_USER_NAME_RF {
            get {
                return ResourceManager.GetString("SIGNUP_MISSING_USER_NAME_RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Username &amp; Password is a threat to account security..
        /// </summary>
        public static string SIGNUP_USER_NAME_AND_PASSWORD_SAME_V {
            get {
                return ResourceManager.GetString("SIGNUP_USER_NAME_AND_PASSWORD_SAME_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not incur any adjusted gross Income deductions.
        /// </summary>
        public static string TAX_PAYER_ADJUSTED_GROSS_INCOME_DEPENDENT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_ADJUSTED_GROSS_INCOME_DEPENDENT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) must be under the age of 65 as of January 1, 2014..
        /// </summary>
        public static string TAX_PAYER_AGE_CALCULATION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_AGE_CALCULATION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not subject to AMT taxes on your personal tax return. And you are not allowed to claim your Prior year minimum tax credit on your tax return.
        /// </summary>
        public static string TAX_PAYER_AMT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_AMT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not be claimed as debtor in a Chapter 11 bankruptcy case filed after October 16, 2005.
        /// </summary>
        public static string TAX_PAYER_BANKRUPTY_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_BANKRUPTY_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not be legally blind as of January 1, 2014..
        /// </summary>
        public static string TAX_PAYER_BLIEND_CHECK_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_BLIEND_CHECK_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TAX_PAYER_DEDUCATION_AND_CREDITS_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_DEDUCATION_AND_CREDITS_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not claim any credits with the exception of EIC.
        /// </summary>
        public static string TAX_PAYER_EIC_CREDITS_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_EIC_CREDITS_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not eligible to file form 1040EZ.You can file 1040 (or) 1040A.
        /// </summary>
        public static string TAX_PAYER_ELIGIBILITY_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_ELIGIBILITY_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have made estimated tax payments for federal and state.
        /// </summary>
        public static string TAX_PAYER_ESTIMATE_TAX_PAYMENT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_ESTIMATE_TAX_PAYMENT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your filing status must be Single or Married Filing Jointly.
        /// </summary>
        public static string TAX_PAYER_FILING_STATUS_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_FILING_STATUS_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not subject to any household employment taxes on wages paid to household employees..
        /// </summary>
        public static string TAX_PAYER_HOUSEHOLD_EMPLOYMENT_TAX_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_HOUSEHOLD_EMPLOYMENT_TAX_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not have any other taxable Income apart from Wages, Unemployment compensation and Interest Income..
        /// </summary>
        public static string TAX_PAYER_INCOME_FROM_OTHER_SOURCE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_INCOME_FROM_OTHER_SOURCE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not be legally blind as of January 1, 2014..
        /// </summary>
        public static string TAX_PAYER_IS_LEGALLY_BLIND_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_IS_LEGALLY_BLIND_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not claim any Itemized deductions.
        /// </summary>
        public static string TAX_PAYER_ITEMIZED_DEDUCTIONS_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_ITEMIZED_DEDUCTIONS_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not claim any dependents on your personal tax return.
        /// </summary>
        public static string TAX_PAYER_PERSONAL_TAX_CLAIM_DEPENDENT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_PERSONAL_TAX_CLAIM_DEPENDENT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You &amp; your Spouse (if MFJ) should not have any taxable social security Benefits or Railroad benefits Income on your tax return..
        /// </summary>
        public static string TAX_PAYER_SOCIAL_SECURITY_BENEFITS_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_SOCIAL_SECURITY_BENEFITS_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your taxable Income for the year should be less than $100,000..
        /// </summary>
        public static string TAX_PAYER_TAXABLE_INCOME_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_TAXABLE_INCOME_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your taxable Interest Income on Form 1040EZ (Line 2) should be less than $1,500..
        /// </summary>
        public static string TAX_PAYER_TAXABLE_INTEREST_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("TAX_PAYER_TAXABLE_INTEREST_ERROR_MESSAGE", resourceCulture);
            }
        }
    }
}
