//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTL.Tax1040.EfileServices.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class efile_comment
    {
        public long efile_comment_id { get; set; }
        public Nullable<long> efile_hold_id { get; set; }
        public string efile_comment1 { get; set; }
        public Nullable<long> admin_users_id { get; set; }
        public Nullable<System.DateTime> create_time_stamp { get; set; }
    
        public virtual efile_hold efile_hold { get; set; }
    }
}
