//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using JTL.Tax1040.BusinessObject;

namespace JTL.Tax1040.BusinessObject
{
    public class PaidTaxReturnPreparers
    {
        public string PreparerName { get; set; }

        public DateTime Date { get; set; }

        public string PTIN { get; set; }

        public Organization Firm { get; set; }

    }

}

