//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*
    Modification History:
    ---------------------
 * 17Apr2014 Ashok kumar Modified datatypes
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JTL.Tax1040.BusinessObject
{
    public class Tax8879Page1
    {
        public string TaxPayerPIN { get; set; }

        public string SpousePIN { get; set; }

    }
}

