//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace JTL.Tax1040.EfileServices.PingService.ETECTransmitterServicesMTOM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetNew2290Schedule1s", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM")]
    public partial class GetNew2290Schedule1s : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallGetNew2290Schedule1sOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetNew2290Schedule1s() {
            this.Url = global::JTL.Tax1040.EfileServices.PingService.Properties.Settings.Default.JTL_Tax1040_EfileServices_PingService_ETECTransmitterServicesMTOM_GetNew2290Schedule1s;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallGetNew2290Schedule1sCompletedEventHandler CallGetNew2290Schedule1sCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/mtom/GetNew2290Schedule1s", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetNew2290Schedule1sResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
        public GetNew2290Schedule1sResponseType CallGetNew2290Schedule1s([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")] GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest) {
            object[] results = this.Invoke("CallGetNew2290Schedule1s", new object[] {
                        GetNew2290Schedule1sRequest});
            return ((GetNew2290Schedule1sResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallGetNew2290Schedule1sAsync(GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest) {
            this.CallGetNew2290Schedule1sAsync(GetNew2290Schedule1sRequest, null);
        }
        
        /// <remarks/>
        public void CallGetNew2290Schedule1sAsync(GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest, object userState) {
            if ((this.CallGetNew2290Schedule1sOperationCompleted == null)) {
                this.CallGetNew2290Schedule1sOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetNew2290Schedule1sOperationCompleted);
            }
            this.InvokeAsync("CallGetNew2290Schedule1s", new object[] {
                        GetNew2290Schedule1sRequest}, this.CallGetNew2290Schedule1sOperationCompleted, userState);
        }
        
        private void OnCallGetNew2290Schedule1sOperationCompleted(object arg) {
            if ((this.CallGetNew2290Schedule1sCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGetNew2290Schedule1sCompleted(this, new CallGetNew2290Schedule1sCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Get2290Schedule1s", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM")]
    public partial class Get2290Schedule1s : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallGet2290Schedule1sOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Get2290Schedule1s() {
            this.Url = "http://localhost:9080/a2a/mef/mtom/Get2290Schedule1s";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallGet2290Schedule1sCompletedEventHandler CallGet2290Schedule1sCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1s", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get2290Schedule1sResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
        public Get2290Schedule1sResponseType CallGet2290Schedule1s([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")] Get2290Schedule1sRequestType Get2290Schedule1sRequest) {
            object[] results = this.Invoke("CallGet2290Schedule1s", new object[] {
                        Get2290Schedule1sRequest});
            return ((Get2290Schedule1sResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1sAsync(Get2290Schedule1sRequestType Get2290Schedule1sRequest) {
            this.CallGet2290Schedule1sAsync(Get2290Schedule1sRequest, null);
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1sAsync(Get2290Schedule1sRequestType Get2290Schedule1sRequest, object userState) {
            if ((this.CallGet2290Schedule1sOperationCompleted == null)) {
                this.CallGet2290Schedule1sOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGet2290Schedule1sOperationCompleted);
            }
            this.InvokeAsync("CallGet2290Schedule1s", new object[] {
                        Get2290Schedule1sRequest}, this.CallGet2290Schedule1sOperationCompleted, userState);
        }
        
        private void OnCallGet2290Schedule1sOperationCompleted(object arg) {
            if ((this.CallGet2290Schedule1sCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGet2290Schedule1sCompleted(this, new CallGet2290Schedule1sCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Get2290Schedule1", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM")]
    public partial class Get2290Schedule1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallGet2290Schedule1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Get2290Schedule1() {
            this.Url = "http://localhost:9080/a2a/mef/mtom/Get2290Schedule1";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallGet2290Schedule1CompletedEventHandler CallGet2290Schedule1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get2290Schedule1Response", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
        public Get2290Schedule1ResponseType CallGet2290Schedule1([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")] Get2290Schedule1RequestType Get2290Schedule1Request) {
            object[] results = this.Invoke("CallGet2290Schedule1", new object[] {
                        Get2290Schedule1Request});
            return ((Get2290Schedule1ResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1Async(Get2290Schedule1RequestType Get2290Schedule1Request) {
            this.CallGet2290Schedule1Async(Get2290Schedule1Request, null);
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1Async(Get2290Schedule1RequestType Get2290Schedule1Request, object userState) {
            if ((this.CallGet2290Schedule1OperationCompleted == null)) {
                this.CallGet2290Schedule1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGet2290Schedule1OperationCompleted);
            }
            this.InvokeAsync("CallGet2290Schedule1", new object[] {
                        Get2290Schedule1Request}, this.CallGet2290Schedule1OperationCompleted, userState);
        }
        
        private void OnCallGet2290Schedule1OperationCompleted(object arg) {
            if ((this.CallGet2290Schedule1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGet2290Schedule1Completed(this, new CallGet2290Schedule1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Get2290Schedule1sByMsgID", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM")]
    public partial class Get2290Schedule1sByMsgID : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallGet2290Schedule1sByMsgIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Get2290Schedule1sByMsgID() {
            this.Url = "http://localhost:9080/a2a/mef/mtom/Get2290Schedule1sByMsgID";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallGet2290Schedule1sByMsgIDCompletedEventHandler CallGet2290Schedule1sByMsgIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1sByMsgID", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Get2290Schedule1sByMsgIDResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
        public Get2290Schedule1sByMsgIDResponseType CallGet2290Schedule1sByMsgID([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")] Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest) {
            object[] results = this.Invoke("CallGet2290Schedule1sByMsgID", new object[] {
                        Get2290Schedule1sByMsgIDRequest});
            return ((Get2290Schedule1sByMsgIDResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1sByMsgIDAsync(Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest) {
            this.CallGet2290Schedule1sByMsgIDAsync(Get2290Schedule1sByMsgIDRequest, null);
        }
        
        /// <remarks/>
        public void CallGet2290Schedule1sByMsgIDAsync(Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest, object userState) {
            if ((this.CallGet2290Schedule1sByMsgIDOperationCompleted == null)) {
                this.CallGet2290Schedule1sByMsgIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGet2290Schedule1sByMsgIDOperationCompleted);
            }
            this.InvokeAsync("CallGet2290Schedule1sByMsgID", new object[] {
                        Get2290Schedule1sByMsgIDRequest}, this.CallGet2290Schedule1sByMsgIDOperationCompleted, userState);
        }
        
        private void OnCallGet2290Schedule1sByMsgIDOperationCompleted(object arg) {
            if ((this.CallGet2290Schedule1sByMsgIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGet2290Schedule1sByMsgIDCompleted(this, new CallGet2290Schedule1sByMsgIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("MeF", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd", IsNullable=false)]
    public partial class MeFHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private string messageIDField;
        
        private string relatesToField;
        
        private string actionField;
        
        private System.DateTime timestampField;
        
        private string eTINField;
        
        private SessionIndicatorType sessionIndicatorField;
        
        private bool sessionIndicatorFieldSpecified;
        
        private TestIndicatorType testIndicatorField;
        
        private bool testIndicatorFieldSpecified;
        
        private MeFNotificationResponse notificationResponseField;
        
        private string appSysIDField;
        
        private string wSDLVersionField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public MeFHeaderType() {
            this.wSDLVersionField = "9.0";
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string RelatesTo {
            get {
                return this.relatesToField;
            }
            set {
                this.relatesToField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string ETIN {
            get {
                return this.eTINField;
            }
            set {
                this.eTINField = value;
            }
        }
        
        /// <remarks/>
        public SessionIndicatorType SessionIndicator {
            get {
                return this.sessionIndicatorField;
            }
            set {
                this.sessionIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SessionIndicatorSpecified {
            get {
                return this.sessionIndicatorFieldSpecified;
            }
            set {
                this.sessionIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TestIndicatorType TestIndicator {
            get {
                return this.testIndicatorField;
            }
            set {
                this.testIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestIndicatorSpecified {
            get {
                return this.testIndicatorFieldSpecified;
            }
            set {
                this.testIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MeFNotificationResponse NotificationResponse {
            get {
                return this.notificationResponseField;
            }
            set {
                this.notificationResponseField = value;
            }
        }
        
        /// <remarks/>
        public string AppSysID {
            get {
                return this.appSysIDField;
            }
            set {
                this.appSysIDField = value;
            }
        }
        
        /// <remarks/>
        public string WSDLVersion {
            get {
                return this.wSDLVersionField;
            }
            set {
                this.wSDLVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum SessionIndicatorType {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum TestIndicatorType {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class MeFNotificationResponse {
        
        private string notificationTypeField;
        
        private System.DateTime applicableDateField;
        
        /// <remarks/>
        public string NotificationType {
            get {
                return this.notificationTypeField;
            }
            set {
                this.notificationTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApplicableDate {
            get {
                return this.applicableDateField;
            }
            set {
                this.applicableDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sByMsgIDResponseType {
        
        private string countField;
        
        private bool moreAvailableField;
        
        private base64Binary schedule1AttachmentMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public bool MoreAvailable {
            get {
                return this.moreAvailableField;
            }
            set {
                this.moreAvailableField = value;
            }
        }
        
        /// <remarks/>
        public base64Binary Schedule1AttachmentMTOM {
            get {
                return this.schedule1AttachmentMTOMField;
            }
            set {
                this.schedule1AttachmentMTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sByMsgIDRequestType {
        
        private string messageIDField;
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1ResponseType {
        
        private base64Binary schedule1AttachmentMTOMField;
        
        /// <remarks/>
        public base64Binary Schedule1AttachmentMTOM {
            get {
                return this.schedule1AttachmentMTOMField;
            }
            set {
                this.schedule1AttachmentMTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1RequestType {
        
        private string submissionIdField;
        
        /// <remarks/>
        public string SubmissionId {
            get {
                return this.submissionIdField;
            }
            set {
                this.submissionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class MeFErrorType {
        
        private string errorMessageField;
        
        private ErrorClassificationType errorClassificationField;
        
        private string errorCodeField;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public ErrorClassificationType ErrorClassification {
            get {
                return this.errorClassificationField;
            }
            set {
                this.errorClassificationField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public enum ErrorClassificationType {
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        RESOURCE_UNAVAILABLE,
        
        /// <remarks/>
        MESSAGE_FORMAT_ERROR,
        
        /// <remarks/>
        SECURITY_ERROR,
        
        /// <remarks/>
        REQUEST_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class SubmissionErrorType {
        
        private string submissionIdField;
        
        private MeFErrorType errorField;
        
        /// <remarks/>
        public string SubmissionId {
            get {
                return this.submissionIdField;
            }
            set {
                this.submissionIdField = value;
            }
        }
        
        /// <remarks/>
        public MeFErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sResponseType {
        
        private string countField;
        
        private SubmissionErrorType[] listOfSubmissionErrorField;
        
        private base64Binary schedule1AttachmentMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionError", IsNullable=false)]
        public SubmissionErrorType[] ListOfSubmissionError {
            get {
                return this.listOfSubmissionErrorField;
            }
            set {
                this.listOfSubmissionErrorField = value;
            }
        }
        
        /// <remarks/>
        public base64Binary Schedule1AttachmentMTOM {
            get {
                return this.schedule1AttachmentMTOMField;
            }
            set {
                this.schedule1AttachmentMTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sRequestType {
        
        private string[] submissionIdListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionId", IsNullable=false)]
        public string[] SubmissionIdList {
            get {
                return this.submissionIdListField;
            }
            set {
                this.submissionIdListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class GetNew2290Schedule1sResponseType {
        
        private string countField;
        
        private bool moreAvailableField;
        
        private base64Binary schedule1AttachmentMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public bool MoreAvailable {
            get {
                return this.moreAvailableField;
            }
            set {
                this.moreAvailableField = value;
            }
        }
        
        /// <remarks/>
        public base64Binary Schedule1AttachmentMTOM {
            get {
                return this.schedule1AttachmentMTOMField;
            }
            set {
                this.schedule1AttachmentMTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class GetNew2290Schedule1sRequestType {
        
        private string maxResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string MaxResults {
            get {
                return this.maxResultsField;
            }
            set {
                this.maxResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallGetNew2290Schedule1sCompletedEventHandler(object sender, CallGetNew2290Schedule1sCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGetNew2290Schedule1sCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGetNew2290Schedule1sCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetNew2290Schedule1sResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetNew2290Schedule1sResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallGet2290Schedule1sCompletedEventHandler(object sender, CallGet2290Schedule1sCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGet2290Schedule1sCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGet2290Schedule1sCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Get2290Schedule1sResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Get2290Schedule1sResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallGet2290Schedule1CompletedEventHandler(object sender, CallGet2290Schedule1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGet2290Schedule1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGet2290Schedule1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Get2290Schedule1ResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Get2290Schedule1ResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallGet2290Schedule1sByMsgIDCompletedEventHandler(object sender, CallGet2290Schedule1sByMsgIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGet2290Schedule1sByMsgIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGet2290Schedule1sByMsgIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Get2290Schedule1sByMsgIDResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Get2290Schedule1sByMsgIDResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591