//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace JTL.Tax1040.EfileServices.PingService.MeFMSIServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChangePassword", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class ChangePassword : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallChangePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChangePassword() {
            this.Url = global::JTL.Tax1040.EfileServices.PingService.Properties.Settings.Default.JTL_Tax1040_EfileServices_PingService_MeFMSIServices_ChangePassword;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallChangePasswordCompletedEventHandler CallChangePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/ChangePassword", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ChangePasswordResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public ChangePasswordResponseType CallChangePassword([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] ChangePasswordRequestType ChangePasswordRequest) {
            object[] results = this.Invoke("CallChangePassword", new object[] {
                        ChangePasswordRequest});
            return ((ChangePasswordResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallChangePasswordAsync(ChangePasswordRequestType ChangePasswordRequest) {
            this.CallChangePasswordAsync(ChangePasswordRequest, null);
        }
        
        /// <remarks/>
        public void CallChangePasswordAsync(ChangePasswordRequestType ChangePasswordRequest, object userState) {
            if ((this.CallChangePasswordOperationCompleted == null)) {
                this.CallChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallChangePasswordOperationCompleted);
            }
            this.InvokeAsync("CallChangePassword", new object[] {
                        ChangePasswordRequest}, this.CallChangePasswordOperationCompleted, userState);
        }
        
        private void OnCallChangePasswordOperationCompleted(object arg) {
            if ((this.CallChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallChangePasswordCompleted(this, new CallChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EtinRetrieval", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class EtinRetrieval : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallEtinRetrievalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EtinRetrieval() {
            this.Url = "http://www.irs.gov/a2a/mef/EtinRetrieval";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallEtinRetrievalCompletedEventHandler CallEtinRetrievalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/EtinRetrieval", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EtinRetrievalResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public EtinRetrievalResponseType CallEtinRetrieval([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] EtinRetrievalRequestType EtinRetrievalRequest) {
            object[] results = this.Invoke("CallEtinRetrieval", new object[] {
                        EtinRetrievalRequest});
            return ((EtinRetrievalResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallEtinRetrievalAsync(EtinRetrievalRequestType EtinRetrievalRequest) {
            this.CallEtinRetrievalAsync(EtinRetrievalRequest, null);
        }
        
        /// <remarks/>
        public void CallEtinRetrievalAsync(EtinRetrievalRequestType EtinRetrievalRequest, object userState) {
            if ((this.CallEtinRetrievalOperationCompleted == null)) {
                this.CallEtinRetrievalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallEtinRetrievalOperationCompleted);
            }
            this.InvokeAsync("CallEtinRetrieval", new object[] {
                        EtinRetrievalRequest}, this.CallEtinRetrievalOperationCompleted, userState);
        }
        
        private void OnCallEtinRetrievalOperationCompleted(object arg) {
            if ((this.CallEtinRetrievalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallEtinRetrievalCompleted(this, new CallEtinRetrievalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EtinStatus", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class EtinStatus : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallEtinStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EtinStatus() {
            this.Url = "http://www.irs.gov/a2a/mef/EtinStatus";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallEtinStatusCompletedEventHandler CallEtinStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/EtinStatus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EtinStatusResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public EtinStatusResponseType CallEtinStatus([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] EtinStatusRequestType EtinStatusRequest) {
            object[] results = this.Invoke("CallEtinStatus", new object[] {
                        EtinStatusRequest});
            return ((EtinStatusResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallEtinStatusAsync(EtinStatusRequestType EtinStatusRequest) {
            this.CallEtinStatusAsync(EtinStatusRequest, null);
        }
        
        /// <remarks/>
        public void CallEtinStatusAsync(EtinStatusRequestType EtinStatusRequest, object userState) {
            if ((this.CallEtinStatusOperationCompleted == null)) {
                this.CallEtinStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallEtinStatusOperationCompleted);
            }
            this.InvokeAsync("CallEtinStatus", new object[] {
                        EtinStatusRequest}, this.CallEtinStatusOperationCompleted, userState);
        }
        
        private void OnCallEtinStatusOperationCompleted(object arg) {
            if ((this.CallEtinStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallEtinStatusCompleted(this, new CallEtinStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetStateParticipantsList", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class GetStateParticipantsList : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallGetStateParticipantsListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetStateParticipantsList() {
            this.Url = "http://www.irs.gov/a2a/mef/GetStateParticipantsList";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallGetStateParticipantsListCompletedEventHandler CallGetStateParticipantsListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/GetStateParticipantsList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStateParticipantsListResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public GetStateParticipantsListResponseType CallGetStateParticipantsList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] GetStateParticipantsListRequestType GetStateParticipantsListRequest) {
            object[] results = this.Invoke("CallGetStateParticipantsList", new object[] {
                        GetStateParticipantsListRequest});
            return ((GetStateParticipantsListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallGetStateParticipantsListAsync(GetStateParticipantsListRequestType GetStateParticipantsListRequest) {
            this.CallGetStateParticipantsListAsync(GetStateParticipantsListRequest, null);
        }
        
        /// <remarks/>
        public void CallGetStateParticipantsListAsync(GetStateParticipantsListRequestType GetStateParticipantsListRequest, object userState) {
            if ((this.CallGetStateParticipantsListOperationCompleted == null)) {
                this.CallGetStateParticipantsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetStateParticipantsListOperationCompleted);
            }
            this.InvokeAsync("CallGetStateParticipantsList", new object[] {
                        GetStateParticipantsListRequest}, this.CallGetStateParticipantsListOperationCompleted, userState);
        }
        
        private void OnCallGetStateParticipantsListOperationCompleted(object arg) {
            if ((this.CallGetStateParticipantsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGetStateParticipantsListCompleted(this, new CallGetStateParticipantsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InitialLogin", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class InitialLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallInitialLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InitialLogin() {
            this.Url = "http://www.irs.gov/a2a/mef/InitialLogin";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallInitialLoginCompletedEventHandler CallInitialLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/InitialLogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("InitialLoginResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public InitialLoginResponseType CallInitialLogin([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] InitialLoginRequestType InitialLoginRequest) {
            object[] results = this.Invoke("CallInitialLogin", new object[] {
                        InitialLoginRequest});
            return ((InitialLoginResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallInitialLoginAsync(InitialLoginRequestType InitialLoginRequest) {
            this.CallInitialLoginAsync(InitialLoginRequest, null);
        }
        
        /// <remarks/>
        public void CallInitialLoginAsync(InitialLoginRequestType InitialLoginRequest, object userState) {
            if ((this.CallInitialLoginOperationCompleted == null)) {
                this.CallInitialLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallInitialLoginOperationCompleted);
            }
            this.InvokeAsync("CallInitialLogin", new object[] {
                        InitialLoginRequest}, this.CallInitialLoginOperationCompleted, userState);
        }
        
        private void OnCallInitialLoginOperationCompleted(object arg) {
            if ((this.CallInitialLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallInitialLoginCompleted(this, new CallInitialLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Logout", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class Logout : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallLogoutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Logout() {
            this.Url = "http://www.irs.gov/a2a/mef/Logout";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallLogoutCompletedEventHandler CallLogoutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/Logout", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LogoutResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public LogoutResponseType CallLogout([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] LogoutRequestType LogoutRequest) {
            object[] results = this.Invoke("CallLogout", new object[] {
                        LogoutRequest});
            return ((LogoutResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallLogoutAsync(LogoutRequestType LogoutRequest) {
            this.CallLogoutAsync(LogoutRequest, null);
        }
        
        /// <remarks/>
        public void CallLogoutAsync(LogoutRequestType LogoutRequest, object userState) {
            if ((this.CallLogoutOperationCompleted == null)) {
                this.CallLogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallLogoutOperationCompleted);
            }
            this.InvokeAsync("CallLogout", new object[] {
                        LogoutRequest}, this.CallLogoutOperationCompleted, userState);
        }
        
        private void OnCallLogoutOperationCompleted(object arg) {
            if ((this.CallLogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallLogoutCompleted(this, new CallLogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Login", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices")]
    public partial class Login : Microsoft.Web.Services3.WebServicesClientProtocol  {
        
        private MeFHeaderType meFField;
        
        private System.Threading.SendOrPostCallback CallLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Login() {
            this.Url = "http://www.irs.gov/a2a/mef/Login";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MeFHeaderType MeF {
            get {
                return this.meFField;
            }
            set {
                this.meFField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallLoginCompletedEventHandler CallLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MeF", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.irs.gov/a2a/mef/Login", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LoginResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
        public LoginResponseType CallLogin([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")] LoginRequestType LoginRequest) {
            object[] results = this.Invoke("CallLogin", new object[] {
                        LoginRequest});
            return ((LoginResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallLoginAsync(LoginRequestType LoginRequest) {
            this.CallLoginAsync(LoginRequest, null);
        }
        
        /// <remarks/>
        public void CallLoginAsync(LoginRequestType LoginRequest, object userState) {
            if ((this.CallLoginOperationCompleted == null)) {
                this.CallLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallLoginOperationCompleted);
            }
            this.InvokeAsync("CallLogin", new object[] {
                        LoginRequest}, this.CallLoginOperationCompleted, userState);
        }
        
        private void OnCallLoginOperationCompleted(object arg) {
            if ((this.CallLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallLoginCompleted(this, new CallLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("MeF", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd", IsNullable=false)]
    public partial class MeFHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private string messageIDField;
        
        private string relatesToField;
        
        private string actionField;
        
        private System.DateTime timestampField;
        
        private string eTINField;
        
        private SessionIndicatorType sessionIndicatorField;
        
        private bool sessionIndicatorFieldSpecified;
        
        private TestIndicatorType testIndicatorField;
        
        private bool testIndicatorFieldSpecified;
        
        private MeFNotificationResponse notificationResponseField;
        
        private string appSysIDField;
        
        private string wSDLVersionField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public MeFHeaderType() {
            this.wSDLVersionField = "9.0";
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string RelatesTo {
            get {
                return this.relatesToField;
            }
            set {
                this.relatesToField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string ETIN {
            get {
                return this.eTINField;
            }
            set {
                this.eTINField = value;
            }
        }
        
        /// <remarks/>
        public SessionIndicatorType SessionIndicator {
            get {
                return this.sessionIndicatorField;
            }
            set {
                this.sessionIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SessionIndicatorSpecified {
            get {
                return this.sessionIndicatorFieldSpecified;
            }
            set {
                this.sessionIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TestIndicatorType TestIndicator {
            get {
                return this.testIndicatorField;
            }
            set {
                this.testIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestIndicatorSpecified {
            get {
                return this.testIndicatorFieldSpecified;
            }
            set {
                this.testIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MeFNotificationResponse NotificationResponse {
            get {
                return this.notificationResponseField;
            }
            set {
                this.notificationResponseField = value;
            }
        }
        
        /// <remarks/>
        public string AppSysID {
            get {
                return this.appSysIDField;
            }
            set {
                this.appSysIDField = value;
            }
        }
        
        /// <remarks/>
        public string WSDLVersion {
            get {
                return this.wSDLVersionField;
            }
            set {
                this.wSDLVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum SessionIndicatorType {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum TestIndicatorType {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class MeFNotificationResponse {
        
        private string notificationTypeField;
        
        private System.DateTime applicableDateField;
        
        /// <remarks/>
        public string NotificationType {
            get {
                return this.notificationTypeField;
            }
            set {
                this.notificationTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApplicableDate {
            get {
                return this.applicableDateField;
            }
            set {
                this.applicableDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LoginResponseType {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LoginRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LogoutResponseType {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LogoutRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class InitialLoginResponseType {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class InitialLoginRequestType {
        
        private string passwordField;
        
        private string newPasswordField;
        
        private string confirmationTokenField;
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmationToken {
            get {
                return this.confirmationTokenField;
            }
            set {
                this.confirmationTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class StateParticipantType {
        
        private string stateField;
        
        private string participantProgramsField;
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string participantPrograms {
            get {
                return this.participantProgramsField;
            }
            set {
                this.participantProgramsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class GetStateParticipantsListResponseType {
        
        private int countField;
        
        private StateParticipantType[] stateParticipantField;
        
        public GetStateParticipantsListResponseType() {
            this.countField = 0;
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StateParticipant")]
        public StateParticipantType[] StateParticipant {
            get {
                return this.stateParticipantField;
            }
            set {
                this.stateParticipantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class GetStateParticipantsListRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class EtinStatusResponseType {
        
        private string eTINField;
        
        private string statusField;
        
        private ETINFormStatusType[] formField;
        
        /// <remarks/>
        public string ETIN {
            get {
                return this.eTINField;
            }
            set {
                this.eTINField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("form")]
        public ETINFormStatusType[] form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINFormStatusType {
        
        private string formNameField;
        
        private string formStatusField;
        
        /// <remarks/>
        public string formName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
            }
        }
        
        /// <remarks/>
        public string formStatus {
            get {
                return this.formStatusField;
            }
            set {
                this.formStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class EtinStatusRequestType {
        
        private string eTINField;
        
        /// <remarks/>
        public string ETIN {
            get {
                return this.eTINField;
            }
            set {
                this.eTINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINStatusType {
        
        private string eTINField;
        
        private string statusField;
        
        private ETINFormStatusType[] formField;
        
        /// <remarks/>
        public string ETIN {
            get {
                return this.eTINField;
            }
            set {
                this.eTINField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("form")]
        public ETINFormStatusType[] form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class EtinRetrievalResponseType {
        
        private int countField;
        
        private ETINStatusType[] eTINStatusField;
        
        public EtinRetrievalResponseType() {
            this.countField = 0;
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ETINStatus")]
        public ETINStatusType[] ETINStatus {
            get {
                return this.eTINStatusField;
            }
            set {
                this.eTINStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class EtinRetrievalRequestType {
        
        private TestIndicatorType1 testIndicatorField;
        
        /// <remarks/>
        public TestIndicatorType1 TestIndicator {
            get {
                return this.testIndicatorField;
            }
            set {
                this.testIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TestIndicatorType", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public enum TestIndicatorType1 {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ChangePasswordResponseType {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ChangePasswordRequestType {
        
        private string passwordField;
        
        private string newPasswordField;
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallChangePasswordCompletedEventHandler(object sender, CallChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangePasswordResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangePasswordResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallEtinRetrievalCompletedEventHandler(object sender, CallEtinRetrievalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallEtinRetrievalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallEtinRetrievalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EtinRetrievalResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EtinRetrievalResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallEtinStatusCompletedEventHandler(object sender, CallEtinStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallEtinStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallEtinStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EtinStatusResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EtinStatusResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallGetStateParticipantsListCompletedEventHandler(object sender, CallGetStateParticipantsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGetStateParticipantsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGetStateParticipantsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetStateParticipantsListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetStateParticipantsListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallInitialLoginCompletedEventHandler(object sender, CallInitialLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallInitialLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallInitialLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitialLoginResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitialLoginResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallLogoutCompletedEventHandler(object sender, CallLogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallLogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallLogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LogoutResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LogoutResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallLoginCompletedEventHandler(object sender, CallLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591